-- AlterTable
ALTER TABLE "Tour" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tour" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tour" ADD COLUMN "deletedAt" DATETIME;
